### ISSUE TITLE
Put docker infos back to readme?

### ISSUE THREAD

**Issue by LouAdrien** [zebresel-com/mongodm#19]
Are you sure you want to keep the informations related to docker into the contribute file?

It's a bit unnatural to look for these infos there.

Just a thought

**Comment by moehlone** [comment]
The advantage of a separated contribution file on github is that it shows up before anyone is adding an issue or pull request. But I put a part of it it back if its better to discover and link contribution rules to readme. Thanks!

**Comment by LouAdrien** [comment]
Sure, actually you could just make a reference to the contribution file form the readme, as long as you make sure to have the word "docker" and "test" in the paragraph as the common use case is to search for these words :)

Have a nice evening
