### ISSUE TITLE
find by relation

### ISSUE THREAD

**Issue by homina** [zebresel-com/mongodm#4]
how to find by relation?

**Comment by moehlone** [comment]
Hi,

could you explain it by example and give me some more details about what you want to achieve?

Best regards
Philipp

**Comment by homina** [comment]
let say i have a model like this: 
`type Message struct {
	mongodm.DocumentBase `json:",inline" bson:",inline"`

	Sender   interface{} `json:"sender"  bson:"sender" model:"User" relation:"11" required:"true"`
	Receiver interface{} `json:"receiver"  bson:"receiver"  model:"User" relation:"1n" required:"true"`
	Text     string      `json:"text"  bson:"text" minLen:"1" maxLen:"500" required:"true"`
}`
and what i want to achieve is to retrieve all messages with certain sender/receiver id,

**Comment by moehlone** [comment]
If I understand you right, you want to do something like this (with name, id, whatever..):

```go
messages := []*Message{}

err = Message.Find(bson.M{"sender.name" : "Max"}).Exec(&messages)
```
This is currently only possible, if you embed the struct types (like http://stackoverflow.com/questions/26433463/mgo-mongodb-finding-documents-that-match-one-field-from-embedded-struct) or query directly by id.

A fast example with id query would be:

```go
type (

	UserModel struct {
		DocumentBase `json:",inline" bson:",inline"`
		Name     string      `json:"name"  bson:"name" minLen:"1" maxLen:"10" required:"true"`
	}

	MessageModel struct {
		DocumentBase `json:",inline" bson:",inline"`
		Sender   interface{} `json:"sender"  bson:"sender" model:"UserModel" relation:"11" required:"true"`
		Text     string      `json:"text"  bson:"text" minLen:"1" maxLen:"500" required:"true"`
	}
)
```
```go
// Create connection ahead..
User := dbConnection.Model("usermodel")
Message := dbConnection.Model("messagemodel")

user := &UserModel{}
message := &MessageModel{}
message2 := &MessageModel{}

User.New(user)
Message.New(message)
Message.New(message2)

user.Name = "Nils"

err := user.Save()

if err != nil {
    fmt.Println(err)
}

message.Text = "First message"
message.Sender = user

err = message.Save()

if err != nil {
    fmt.Println(err)
}

message2.Text = "Second message"
message2.Sender = user

err = message2.Save()

if err != nil {
   fmt.Println(err)
}

messages := []*MessageModel{}

err = Message.Find(bson.M{"sender" : user.Id}).Populate("Sender").Exec(&messages)

if _, ok := err.(*NotFoundError); ok {
    fmt.Println("No records")
} else if err != nil {
    fmt.Println(err)
} else {
    for _, message := range messages {
        fmt.Println(message.Text)
    }
}
// Output:
// First message
// Second message
```

Do you need any more information?

**Comment by homina** [comment]
ah finally, thanks a lot,

**Comment by moehlone** [comment]
For the receivers you could use the logical operator `$in` with your query..
You`re welcome :)
