### ISSUE TITLE
Slices always viewed as relations

### ISSUE THREAD

**Issue by uzarubin** [zebresel-com/mongodm#5]
Hello there, 

I was wondering if there is a possible bug with how the `relation` tag is handled. I have an `Email` model that holds the sender's email and a slice of recipients. I only want to store the recipient's email, and not the entire user object. The model is written as follows: 

```go 
type Email struct {
	mongodm.DocumentBase `json:",inline" bson:",inline"`
	From	string `json:"from" bson:"from"`
	To 	[]string `json:"to" bson:"to"`
}
```

I am failing validation on the `To` field with `validation.field_invalid_relation1n `. Looking through the document_base.go file I found the following code: 

```go
if fieldValue.Kind() == reflect.Slice && relationTag != REL_1N {
  self.AppendError(&validationErrors, L("validation.field_invalid_relation1n", validationName))
} else if fieldValue.Kind() != reflect.Slice && relationTag == REL_1N {
  self.AppendError(&validationErrors, L("validation.field_invalid_relation11", validationName))
}
```

Shouldn't there be another check inside the if block to see if `relationTag != ""`? Without it, every slice would have to be a relation even though it doesn't need to be.

**Comment by moehlone** [comment]
I will look into this in the next days, thank you!

**Comment by moehlone** [comment]
You were absolutely correct. Thank you :) I put that case also in the tests.

**Comment by uzarubin** [comment]
Awesome! Thanks for taking care of it. : )
