### ISSUE TITLE
Getting Error does not implement DefaultValidate

### ISSUE THREAD

**Issue by ChStark** [zebresel-com/mongodm#6]
Hi, I am new with golang and I tried to use your library and I get the following error

```
middlewares/main.go:76: cannot use model (type models.Model) as type mongodm.IDocumentBase in argument to ModelCollection.New:
	models.Model does not implement mongodm.IDocumentBase (DefaultValidate method has pointer receiver)
```

I have emmbeded the struct `mongodm.DocumentBase` on my definition, what is my problem ?

**Comment by moehlone** [comment]
Hi,

could you send me some more details or (a part of) your project?

**Comment by ChStark** [comment]
Is just a basic struct 

```
type Model struct{
    mongodm.DocumentBase `json:",inline" bson:",inline"`
    ... some other fields
}
```
on the main :

```
connection.Register(&models.Model{}, "Models")
```

And I have a goroutine receiving the struct thru a channel:
```
func Routine() {
	for {
		model := <-ModelChannel
		ModelCollection := connection.Model("Model")
		ModelCollection.New(model)
	}
}
```

**Comment by uzarubin** [comment]
@ChStark Your `model` needs to take a pointer from the `ModelChannel`

**Comment by moehlone** [comment]
@ChStark do you need any more input after the answer of @uzarubin ?
