### ISSUE TITLE
Expanding mongodm.Config

### ISSUE THREAD

**Issue by uzarubin** [zebresel-com/mongodm#7]
Hi there!

I was reading up on `mongodm.Config`, and noticed that `SetSocketTimeOut`, `SetSafe`, and `SetMode` were hardcoded instead of allowing users to pass them in via `mongodm.Config`. Are there any plans to include this functionality in future releases? If you accept PRs, I'd be more than happy to add that in.

**Comment by moehlone** [comment]
Hi @uzarubin,

of course you can open a pull request! I will check and accept them if everything fits.
Please don't forget some testings if needed.

Best regards
Philipp

**Comment by moehlone** [comment]
I will have a look into this at the weekend. Thank you in advance!

**Comment by moehlone** [comment]
Closed with #8
